<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="DESKTOP-GHPND5U" name="testCases.DodavanjeZgradaTest" tests="6" failures="1" timestamp="02 Dec 2019 22:03:40 GMT" time="3.802" errors="0">
  <testcase name="NegativanTestDodavanjaZgrade3" time="1.066" classname="testCases.DodavanjeZgradaTest"/>
  <testcase name="PozitivanTestIstaAdresaZgrade" time="1.639" classname="testCases.DodavanjeZgradaTest">
    <failure type="java.lang.AssertionError" message="expected [Vec postoji zgrada na toj adresi!] but found [Uspesno ste dodali zgradu!]">
      <![CDATA[java.lang.AssertionError: expected [Vec postoji zgrada na toj adresi!] but found [Uspesno ste dodali zgradu!]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testCases.DodavanjeZgradaTest.PozitivanTestIstaAdresaZgrade(DodavanjeZgradaTest.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- PozitivanTestIstaAdresaZgrade -->
  <testcase name="NegativanTestDodavanjaZgrade1" time="1.097" classname="testCases.DodavanjeZgradaTest"/>
  <testcase name="PozitivanTestDodavanjaZgrade" classname="testCases.DodavanjeZgradaTest">
    <skipped/>
  </testcase> <!-- PozitivanTestDodavanjaZgrade -->
  <testcase name="PozitivanTestResetDugme" classname="testCases.DodavanjeZgradaTest">
    <skipped/>
  </testcase> <!-- PozitivanTestResetDugme -->
  <testcase name="NegativanTestDodavanjaZgrade2" classname="testCases.DodavanjeZgradaTest">
    <skipped/>
  </testcase> <!-- NegativanTestDodavanjaZgrade2 -->
</testsuite> <!-- testCases.DodavanjeZgradaTest -->
